version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=uezdb
    volumes:
      - uezdb_pg_data:/bitnami/postgresql

volumes:
  uezdb_pg_data:
